[package]
name = "minimal"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
yew = { path = "../../yew" }
wasm-bindgen = "0.2.64"
