[package]
name = "crm"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
common = { path = "../common" }
serde = "1"
serde_derive = "1"
yew = { path = "../../yew" }
